#!/usr/bin/env python3
"""Auto-generate sessions/binds.json from the player's own Riot cloud settings.

Reads the signed-in client's tokens (lockfile), fetches player preferences
(usw2.pp.sgp.pvp.net), decodes the blob, and maps ability binds to the capture
kinds the input tap records. Run once per player/machine (and after rebinding).
"""
import base64, json, os, ssl, subprocess, sys, zlib, urllib.request

BASE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(BASE, "sessions", "binds.json")

# Riot key name -> capture kind the tap writes
KEY_TO_KIND = {"C": "c", "Q": "q", "E": "e", "X": "x",
               "One": "1", "Two": "2", "Three": "3",
               "ThumbMouseButton": "m4", "ThumbMouseButton2": "m5"}
SLOTS = {"Activate_GrenadeAbility": "grenade", "Activate_Ability1": "ability1",
         "Activate_Ability2": "signature", "Activate_Ultimate": "ult"}
DEFAULT_KEYS = {"Activate_GrenadeAbility": "C", "Activate_Ability1": "Q",
                "Activate_Ability2": "E", "Activate_Ultimate": "X"}


def main():
    lock = open(os.path.join(os.environ["LOCALAPPDATA"], "Riot Games",
                             "Riot Client", "Config", "lockfile")).read().strip().split(":")
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    req = urllib.request.Request(f"https://127.0.0.1:{lock[2]}/entitlements/v1/token")
    req.add_header("Authorization", "Basic " +
                   base64.b64encode(f"riot:{lock[3]}".encode()).decode())
    ent = json.loads(urllib.request.urlopen(req, timeout=5, context=ctx).read())
    tmp = os.path.join(BASE, "sessions", "_prefs.tmp")
    r = subprocess.run(
        ["curl.exe", "-s", "-o", tmp, "-w", "%{http_code}",
         "https://usw2.pp.sgp.pvp.net/playerPref/v3/getPreference/Ares.PlayerSettings",
         "-H", f"Authorization: Bearer {ent['accessToken']}",
         "-H", f"X-Riot-Entitlements-JWT: {ent['token']}",
         "-H", "User-Agent: ShooterGame/18 Windows/10.0.19043.1.256.64bit"],
        capture_output=True, text=True, timeout=30)
    if r.stdout.strip() != "200":
        print(f"prefs fetch failed ({r.stdout.strip()}); writing default binds")
        prefs = {}
    else:
        raw = json.load(open(tmp))
        prefs = json.loads(zlib.decompress(base64.b64decode(raw["data"]),
                                           -zlib.MAX_WBITS))
    try:
        os.remove(tmp)
    except Exception:
        pass

    # overrides: prefer characterName == "None" (global) rows, bindIndex 0
    keys = dict(DEFAULT_KEYS)
    for a in prefs.get("actionMappings", []):
        if a.get("name") in SLOTS and a.get("characterName") in ("None", None) \
                and a.get("bindIndex") == 0 and a.get("key") not in (None, "None"):
            keys[a["name"]] = a["key"]

    equips, uncaptured = {}, []
    for action, slot in SLOTS.items():
        kind = KEY_TO_KIND.get(keys.get(action, ""))
        if kind:
            equips[kind] = slot
        else:
            uncaptured.append({action: keys.get(action)})

    sens = None
    for s in prefs.get("floatSettings", []) or []:
        if "MouseSensitivity" == str(s.get("settingEnum", "")).split("::")[-1]:
            sens = s.get("value")

    binds = {
        "_comment": "auto-generated by fetch_binds.py from Riot player preferences",
        "player": ent.get("subject"),
        "sens": sens,
        "equips": equips,
        "cancels": [k for k in ("q", "1", "2", "3") if k not in equips],
        "confirm_window_s": 4,
        "uncaptured_ability_keys": uncaptured,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    json.dump(binds, open(OUT, "w"), indent=1)
    print(json.dumps(binds, indent=1))
    if uncaptured:
        print("\nWARNING: some ability keys are outside the tap's capture set; "
              "those casts won't be tracked yet:", uncaptured)


if __name__ == "__main__":
    main()
